spring.application.name=giftapp-backend

# MySQL Configuration
# spring.datasource.url=jdbc:mysql://localhost:3306/giftapp?useSSL=false&serverTimezone=UTC
# spring.datasource.username=root
# spring.datasource.password=00000
spring.datasource.url=jdbc:mysql://10.128.222.44:3306/giftapp?autoReconnect=true&useSSL=true&allowLoadLocalInfile=true
# spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=bsp_user
spring.datasource.password=524zf1i6ZdYkuh#
spring.batch.job.enabled=false

# Driver (IMPORTANT)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server
server.port=8080

app.jwt.secret=mysecretkeymysecretkeymysecretkey

# Recommendation Weights
recommendation.gender-weight=20
recommendation.unisex-weight=10
recommendation.occasion-weight=25
recommendation.age-weight=20
recommendation.budget-weight=15
recommendation.colour-weight=20
recommendation.tag-weight=30

# Minimum score threshold
recommendation.min-score=30